- README.md
- src/Header/Header.jsx
- src/Header/Header.test.jsx
- src/Header/SkipLinks/SkipLinks.jsx
- src/Header/SkipLinks/SkipLinks.module.scss
- src/Header/SkipLinks/SkipLinks.test.jsx
- src/Header/SkipLinks/__snapshots__/SkipLinks.test.jsx.snap
- src/Header/SkipLinks/index.js
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-3
> GN-3 Add skip links

- README.md
- examples/index.html
- package-lock.json
- package.json
- src/Header/CookieBanner/CookieBanner.jsx
- src/Header/CookieBanner/CookieBanner.module.scss
- src/Header/CookieBanner/CookieBanner.test.jsx
- src/Header/CookieBanner/__snapshots__/CookieBanner.test.jsx.snap
- src/Header/CookieBanner/index.js
- src/Header/Header.jsx
- src/Header/Header.module.scss
- src/Header/Header.test.jsx
- src/Header/__snapshots__/Header.test.jsx.snap
- webpack.config.js
https://nicedigital.atlassian.net/browse/GN-6
> GN-6 Add cookie banner

- README.md
- examples/examples.json
- src/Header/Account/Account.jsx
- src/Header/Account/Account.test.jsx
- src/Header/Account/nice-accounts.js
- src/Header/Header.jsx
- src/Header/Nav/Nav.module.scss
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-5
> GN-5 NICE Accounts integration

- examples/example.html
https://nicedigital.atlassian.net/browse/GN-5
> GN-5 Add HotJar snippet

- src/Header/CookieBanner/CookieBanner.jsx
- src/Header/CookieBanner/__snapshots__/CookieBanner.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-6
> GN-6 Update copy to match card

- src/Header/TLSMessage/TLSMessage.jsx
https://nicedigital.atlassian.net/browse/GN-7
> GN-7 Change TLS message URL on nice website

- examples/index.html
https://nicedigital.atlassian.net/browse/GN-6
> GN-6 Fix cookie delete button

- examples/body-html/cks.body.html
- examples/examples.json
https://nicedigital.atlassian.net/browse/GN-3
> GN-3 Add skip link example to CKS

- examples/body-html/bnfc.body.html
https://nicedigital.atlassian.net/browse/GN-3
> GN-3 Fix 404 on BNFc test page

- examples/example.html
- package-lock.json
- package.json
- src/Footer/Social/Social.module.scss
- src/Footer/_settings.scss
- src/Header/Account/Account.module.scss
- src/Header/CookieBanner/CookieBanner.module.scss
- src/Header/Header.module.scss
- src/Header/Nav/Nav.module.scss
- src/Header/Search/Autocomplete/Autocomplete.module.scss
- src/Header/Search/Search.module.scss
- src/Header/SkipLinks/SkipLinks.module.scss
- src/Header/TLSMessage/TLSMessage.module.scss
- src/scss/_mq.scss
- webpack.config.js
https://nicedigital.atlassian.net/browse/GN-1
> GN-7 Fix IE8 issues

- src/Header/Account/Account.jsx
- src/Header/Account/Account.test.jsx
- src/Header/Account/__snapshots__/Account.test.jsx.snap
- src/Header/Header.jsx
- src/Header/Header.test.jsx
- src/Header/Nav/Nav.jsx
- src/Header/Nav/Nav.test.jsx
- src/Header/Nav/__snapshots__/Nav.test.jsx.snap
- src/Header/Search/Autocomplete/Autocomplete.jsx
- src/Header/Search/Autocomplete/Autocomplete.test.jsx
- src/Header/__snapshots__/Header.test.jsx.snap
- src/setupTests.js
- src/tracker/index.js
- src/tracker/index.test.js
https://nicedigital.atlassian.net/browse/GN-13
> GN-13 Add GTM tracking

- src/Header/Search/Autocomplete/suggester/term-finder.js
https://nicedigital.atlassian.net/browse/GN-18
> GN-18 Fix autocomplete in IE9+

- README.md
https://nicedigital.atlassian.net/browse/GN-12
> GN-12 Update readme

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/GN-20
See https://www.npmjs.com/advisories/803
https://github.com/sass/node-sass/issues/2625
https://github.com/nodejs/node-gyp/issues/1714
> GN-20 Fix tar vulnerability

- src/Header/Search/Search.jsx
- src/Header/Search/Search.test.jsx
- src/Header/Search/__snapshots__/Search.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-19
> GN-19 Fix onSearching callback not working in IE8

- src/Header/SkipLinks/SkipLinks.jsx
- src/Header/SkipLinks/SkipLinks.test.jsx
https://nicedigital.atlassian.net/browse/GN-21
> GN-21 Fix skip link not scrolling window

- examples/example.html
- src/Header/Header.module.scss
- src/polyfill/array.filter.js
- src/polyfill/array.foreach.js
- src/polyfill/array.isarray.js
- src/polyfill/event.js
- src/polyfill/function.bind.js
- src/polyfill/helpers.js
- src/polyfill/index.js
- src/polyfill/object.create.js
- src/polyfill/object.defineproperty.js
- src/polyfill/object.getOwnPropertyDescriptor.js
- src/polyfill/object.keys.js
- webpack.config.js
https://nicedigital.atlassian.net/browse/GN-22
> GN-22 Fix evidence typeahead not working in IE8

- src/Header/CookieBanner/CookieBanner.jsx
- src/Header/CookieBanner/CookieBanner.test.jsx
https://nicedigital.atlassian.net/browse/GN-24
> GN-24 Evidence Cookie banner issue

- src/Header/Nav/Nav.module.scss
[https://nicedigital.atlassian.net/browse/GN-25](https://nicedigital.atlassian.net/browse/GN-25)
> GN-25 Added more specificity to a links in menu

- src/Header/Search/Autocomplete/Autocomplete.jsx
- src/Header/Search/Autocomplete/Autocomplete.test.jsx
https://nicedigital.atlassian.net/browse/GN-33
> GN-33 Implement debounce algorithm to limit network requests

- src/Header/Nav/Nav.jsx
- src/Header/Nav/__snapshots__/Nav.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-32
> GN-32 Ensure main nav landmark is unique

- README.md
- examples/body-html/identityadmin-loggedin.body.html
- examples/body-html/identityadmin-loggedout.body.html
- examples/examples.js
- package-lock.json
- src/Header/Account/Account.jsx
- src/Header/Account/Account.test.jsx
- src/Header/Account/__snapshots__/Account.test.jsx.snap
- src/Header/Account/nice-accounts.js
- src/Header/Header.jsx
- src/Header/Nav/Nav.jsx
- types.d.ts
https://nicedigital.atlassian.net/browse/IDAM-248
> IDAM-248 Identity management update

- .vscode/settings.json
- examples/body-html/blank.body.html
- examples/examples.js
- package-lock.json
- package.json
- src/Footer/Footer.module.scss
- src/Footer/Legal/Legal.module.scss
- src/Header/CookieBanner/CookieBanner.module.scss
- src/Header/Header.module.scss
- src/Header/Nav/Nav.module.scss
- src/Header/SkipLinks/SkipLinks.module.scss
- webpack.config.prod.js
https://nicedigital.atlassian.net/browse/GN-36
> GN-36 Print styling

- src/Header/Search/Autocomplete/Autocomplete.jsx
- src/Header/Search/Autocomplete/Autocomplete.test.jsx
https://nicedigital.atlassian.net/browse/GN-37
> GN-37 Track New Typeahead

- src/Header/CoronaMessage/CoronaMessage.jsx
- src/Header/CoronaMessage/CoronaMessage.module.scss
- src/Header/CoronaMessage/CoronaMessage.test.jsx
- src/Header/CoronaMessage/__snapshots__/CoronaMessage.test.jsx.snap
- src/Header/CoronaMessage/index.js
- src/Header/Header.jsx
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-41
> GN-41 Add coronavirus message

- src/Header/CookieBanner/CookieBanner.test.jsx
- src/Header/CoronaMessage/CoronaMessage.jsx
- src/Header/CoronaMessage/CoronaMessage.module.scss
- src/Header/CoronaMessage/CoronaMessage.test.jsx
- src/Header/CoronaMessage/__snapshots__/CoronaMessage.test.jsx.snap
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-42
> GN-42 Add ability to minimise COVID banner with cookie storage

- README.md
- examples/examples.js
- src/Header/CookieBanner/CookieBanner.jsx
- src/Header/CookieBanner/CookieBanner.test.jsx
- src/Header/CoronaMessage/CoronaMessage.jsx
- src/Header/CoronaMessage/CoronaMessage.test.jsx
- src/Header/Header.jsx
- src/Header/Header.test.jsx
- types.d.ts
https://nicedigital.atlassian.net/browse/GN-44
> GN-44 Resize handler

- src/Header/CoronaMessage/CoronaMessage.jsx
- src/Header/CoronaMessage/CoronaMessage.test.jsx
- src/Header/CoronaMessage/__snapshots__/CoronaMessage.test.jsx.snap
https://nicedigital.atlassian.net/browse/GW-270
> GW-270 COVID banner rewording

- src/Header/Header.jsx
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-46
> GN-46 Move COVID aside out of header

- src/Footer/Pages/Pages.test.jsx
- src/Footer/Pages/links.json
The form has been removed from Orchard
https://nicedigital.atlassian.net/browse/GN-40
> GN-40 Remove CKS feedback link

- .npmignore
- babel.config.js
- package.json
- src/Header/Header.jsx
- types.d.ts
- webpack.config.js
https://nicedigital.atlassian.net/browse/GN-49
- Fix issue installing from github
- Fix type def for auth property on header
- Fix prop types for auth property on header
- Fix hot loader issue
> GN-49 Tweaks

- .gitignore
- package.json
https://nicedigital.atlassian.net/browse/GN-50
> GN-50 Quote copyfiles operation

- src/Header/Nav/SubNav/SubNav.jsx
https://nicedigital.atlassian.net/browse/CKS-393
> CKS-393 Allow aria label to be used for identifying tracking links

- src/Header/Search/Autocomplete/Autocomplete.jsx
- src/Header/Search/Autocomplete/Autocomplete.test.jsx
- src/Header/Search/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-55
> GN-55 Update hotjar to use "allow"

- src/Footer/Footer.module.scss
- src/Footer/Legal/Legal.jsx
- src/Footer/Legal/__snapshots__/Legal.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-68
> GN-68 Add cookie statement link to footer

- .gitignore
- src/Header/CoronaMessage/CoronaMessage.jsx
- src/Header/CoronaMessage/__snapshots__/CoronaMessage.test.jsx.snap
- src/Header/Header.jsx
- src/Header/Header.test.jsx
- src/Header/Nav/SubNav/SubNav.jsx
- src/Header/Nav/SubNav/__snapshots__/SubNav.test.jsx.snap
- src/Header/Nav/__snapshots__/Nav.test.jsx.snap
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-69
> GN-69 A11y & Skip link h1

- package-lock.json
- package.json
- src/Common.module.scss
- src/Footer/Footer.module.scss
- src/Footer/Services/Services.jsx
- src/Footer/Services/Services.module.scss
- src/Footer/Services/__snapshots__/Services.test.jsx.snap
- src/Header/Header.module.scss
- src/Header/Nav/Nav.jsx
- src/Header/Nav/Nav.module.scss
- src/Header/Nav/SubNav/SubNav.jsx
- src/Header/Nav/SubNav/__snapshots__/SubNav.test.jsx.snap
- src/Header/Nav/__snapshots__/Nav.test.jsx.snap
- src/Header/Search/Autocomplete/Autocomplete.module.scss
https://nicedigital.atlassian.net/browse/GN-80
> GN-80 Evidence search retest tasks

- src/services.json
https://nicedigital.atlassian.net/browse/GN-82
> GN-82 Rename health topics for CKS

- src/Footer/Services/Services.module.scss
- src/Header/Nav/Nav.module.scss
https://nicedigital.atlassian.net/browse/GN-83
> GN-83 Fix CSS import paths

- src/Header/Search/Autocomplete/Autocomplete.jsx
- src/Header/Search/Autocomplete/Autocomplete.test.jsx
- src/Header/Search/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-38
> GN-38 Add 512 character max length

- src/Header/Search/Autocomplete/Autocomplete.jsx
- src/Header/Search/Autocomplete/Autocomplete.test.jsx
- src/Header/Search/Autocomplete/__snapshots__/Autocomplete.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-85
> GN-95 Hydration issue with autocomplete

- src/Header/Search/Search.jsx
- src/Header/Search/Search.test.jsx
- src/Header/Search/__snapshots__/Search.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-85
> GN-85 Fix issue with enter key press not working

- package-lock.json
https://nicedigital.atlassian.net/browse/GN-87
> GN-87 Update deps

- .eslintignore
- .vscode/settings.json
- README.md
- src/Header/Search/Autocomplete/Autocomplete.jsx
- src/Header/Search/Search.jsx
- types.d.ts
https://nicedigital.atlassian.net/browse/GN-86
> GN-86 Document TitleHtml field

- src/Header/Nav/Nav.module.scss
https://nicedigital.atlassian.net/browse/GN-88
> GN-88 Fix wrapping with main navigation on tablets

- package-lock.json
- src/Footer/Services/__snapshots__/Services.test.jsx.snap
- src/Header/Nav/Nav.module.scss
- src/services.json
https://nicedigital.atlassian.net/browse/NAV1-1
> NAV1-1 Life sciences link

- src/Header/Nav/Dropdown/Components/AboutUs.jsx
- src/Header/Nav/Dropdown/Components/BNF.jsx
- src/Header/Nav/Dropdown/Components/BNFc.jsx
- src/Header/Nav/Dropdown/Components/CKS.jsx
- src/Header/Nav/Dropdown/Components/Guidance.jsx
- src/Header/Nav/Dropdown/Components/LifeSciences.jsx
- src/Header/Nav/Dropdown/Components/StandardsAndIndicators.jsx
- src/Header/Nav/NavLinks/NavLinks.jsx
- src/services.json
https://nicedigital.atlassian.net/browse/GN-138
> GN-138 Shorten nav copy

- src/Header/Nav/Dropdown/Components/AboutUs.jsx
- src/Header/Nav/Dropdown/Components/BNF.jsx
- src/Header/Nav/Dropdown/Components/BNFc.jsx
- src/Header/Nav/Dropdown/Components/CKS.jsx
- src/Header/Nav/Dropdown/Components/Grid.jsx
- src/Header/Nav/Dropdown/Components/Grid.module.scss
- src/Header/Nav/Dropdown/Components/Guidance.jsx
- src/Header/Nav/Dropdown/Components/LifeSciences.jsx
- src/Header/Nav/Dropdown/Components/More.jsx
https://nicedigital.atlassian.net/browse/GN-145
> GN-145 Implement self contained grid system

- src/Header/Nav/Dropdown/Components/AboutUs.jsx
- src/Header/Nav/Dropdown/Components/BNF.jsx
- src/Header/Nav/Dropdown/Components/BNFc.jsx
- src/Header/Nav/Dropdown/Components/CKS.jsx
- src/Header/Nav/Dropdown/Components/Guidance.jsx
- src/Header/Nav/Dropdown/Components/LifeSciences.jsx
https://nicedigital.atlassian.net/browse/GN-147
> GN-147 IE11 evidence search

- src/Header/Header.module.scss
https://nicedigital.atlassian.net/browse/GN-148
> GN-148 Fix content overflow

- src/Footer/Footer.module.scss
[GN-157](https://nicedigital.atlassian.net/browse/GN-157)
> GN-157 Change footer z-index to 0 to ensure it appears behind dropdowns

- examples/examples.js
- src/Header/Account/Account.jsx
- src/Header/Account/Account.module.scss
- src/Header/Account/Account.test.jsx
- src/Header/Account/__snapshots__/Account.test.jsx.snap
https://nicedigital.atlassian.net/browse/IDAM-481
> IDAM-481 GN-156 Show-The-Signed-In-Users-Name

- src/Header/Search/Autocomplete/Autocomplete.jsx
https://nicedigital.atlassian.net/browse/GN-167
> GN-167 Change autocomplete rateLimit to 100ms to increase responsiveness

- README.md
- examples/examples.js
- src/Header/Header.jsx
- src/Header/Header.test.jsx
- src/Header/Nav/SubNav/SubNav.jsx
- src/Header/Search/Autocomplete/Autocomplete.jsx
- src/Header/Search/Search.jsx
- src/utils.js
- types.d.ts
https://nicedigital.atlassian.net/browse/GN-169
> GN 169 Dropdown open and close hooks

- README.md
- src/Main/BackToTop/BackToTop.jsx
- src/Main/BackToTop/BackToTop.module.scss
- src/Main/BackToTop/__snapshots__/BackToTop.test.jsx.snap
- src/Main/Main.jsx
- src/Main/Main.module.scss
- src/Main/__snapshots__/Main.test.jsx.snap
- types.d.ts
https://nicedigital.atlassian.net/browse/GN-176
> GN-176 Optional padding on back to top

- src/Header/Nav/Dropdown/Components/AboutUs.jsx
- src/Header/Nav/Dropdown/Components/BNF.jsx
- src/Header/Nav/Dropdown/Components/BNFc.jsx
- src/Header/Nav/Dropdown/Components/Components.module.scss
- src/Header/Nav/Dropdown/Components/Grid.jsx
- src/Header/Nav/Dropdown/Components/Guidance.jsx
- src/Header/Nav/Dropdown/Components/LifeSciences.jsx
- src/Header/Nav/Nav.test.jsx
- src/Header/Nav/NavLinks/NavLinks.jsx
- src/Header/Nav/NavLinks/NavLinks.test.jsx
- src/Header/Nav/__mocks__/services.json
- src/Header/Nav/__snapshots__/Nav.test.jsx.snap
- src/services.json
https://nicedigital.atlassian.net/browse/GN-179
> GN-179 GN-178 GN-177 GN-175 GN-174 mega nav content changes

- src/services.json
https://nicedigital.atlassian.net/browse/GN-180
> GN-180 Fix InDev

- src/Main/Main.jsx
- src/Main/__snapshots__/Main.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-181
> GN-181 Remove withPadding prop from render block, causing console error

- src/services.json
https://nicedigital.atlassian.net/browse/GN-170
> GN-170 Add new InDev menu config item

- src/Header/Nav/Dropdown/Components/CKS.jsx
https://nicedigital.atlassian.net/browse/GN-188
> GN-188 Change guidance to advice for CKS

- src/Footer/Services/Services.jsx
https://nicedigital.atlassian.net/browse/GN-197
> GN-197 Fix footer links

- src/services.json
https://nicedigital.atlassian.net/browse/GN-198
> GN-198 Replace Indev nav link

- src/Header/Nav/Dropdown/Components/StandardsAndIndicators.jsx
https://nicedigital.atlassian.net/browse/GN-194
> GN-194 Change indicators list button text

- examples/body-html/guidance.body.html
- src/Header/Nav/Dropdown/Components/Guidance.jsx
https://nicedigital.atlassian.net/browse/GN-202
> GN-202 Add HTE guidance item to guidance dropdown and example page.

- examples/body-html/guidance.body.html
- src/Header/Nav/Dropdown/Components/Guidance.jsx
https://nicedigital.atlassian.net/browse/GN-203
> GN-203 Change text on HTE programme

- src/Footer/Social/Social.jsx
- src/Footer/Social/__snapshots__/Social.test.jsx.snap
- src/Header/Nav/Dropdown/Components/AboutUs.jsx
https://nicedigital.atlassian.net/browse/GN-208
> GN-205, GN-206, GN-208, NAV-78 Make miscellaneous minor updates to nav and footer text

- package-lock.json
- package.json
https://nicedigital.atlassian.net/browse/GN-209
> GN-209 Version bump design system

- src/Footer/Pages/Pages.test.jsx
- src/Footer/Pages/__snapshots__/Pages.test.jsx.snap
- src/Footer/Pages/links.json
- src/Footer/__snapshots__/Footer.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-210
> GN-210 Update footer links to new forms

- src/Header/Nav/Dropdown/Components/LifeSciences.jsx
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-220
> GN-220 Update NICE Advice service description

- src/Header/Nav/NavLinks/NavLinks.module.scss
https://nicedigital.atlassian.net/browse/GN-221
> GN-221 Fix illegible text on current page

- src/Footer/__snapshots__/Footer.test.jsx.snap
- src/Header/Nav/Dropdown/Components/StandardsAndIndicators.jsx
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-224
> GN-224 Update standards and indicators link and snapshots

- package-lock.json
- package.json
- updating to alpha to test across services
> GN-215  Udpate DS dependency to fix visual regressions

- src/Footer/__snapshots__/Footer.test.jsx.snap
- src/Header/Nav/Dropdown/Components/LifeSciences.jsx
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-226
> GN-226 update global nav life sciences

- src/Header/Nav/Dropdown/Components/AboutUs.jsx
- src/Header/Nav/NavLinks/__snapshots__/NavLinks.test.jsx.snap
- src/Header/Nav/__snapshots__/Nav.test.jsx.snap
- src/Header/__snapshots__/Header.test.jsx.snap
https://nicedigital.atlassian.net/browse/GN-225
> Gn 225 please add a new link to about tab
